version: "3.8"

services:
  db:
    image: postgres:15
    container_name: portmanager-db
    environment:
      POSTGRES_USER: yucelcubukk
      POSTGRES_PASSWORD: Ab212121
      POSTGRES_DB: portmanager
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # Gerekirse portu açarsın ama frontend/backend ile konuştuğu sürece gerek yok:
    # ports:
    #   - "5432:5432"

  backend:
    build: ./port-management-backend
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - DB_USER=yucelcubukk
      - DB_HOST=db
      - DB_NAME=portmanager
      - DB_PASSWORD=Ab212121
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build: ./port-management-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
