services:
  backend:
    build: ./port-management-backend
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - DB_USER=yucelcubukk
      - DB_HOST=host.docker.internal
      - DB_NAME=portmanager
      - DB_PASSWORD=Ab212121
      - DB_PORT=5432

  frontend:
    build: ./port-management-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
